version: '3.8'
services:
  emulator_pubsub:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - '8085:8085'

  emulator_firestore:
    image: bitnami/firestore-emulator
    ports:
      - '8080:8080'

  service_generator:
    build: ./service_generator
    environment:
      - PUBSUB_EMULATOR_HOST=emulator_pubsub:8085
    volumes:
      - ./service_generator:/app

  service_processor:
    build: ./service_processor
    environment:
      - PUBSUB_EMULATOR_HOST=emulator_pubsub:8085
      - FIRESTORE_EMULATOR_HOST=emulator_firestore:8080
    volumes:
      - ./service_processor:/app
